# Generated by Django 2.2 on 2019-06-15 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190614_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('text_color', models.CharField(max_length=7)),
                ('express', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('uptown_stop_number', models.IntegerField()),
                ('downtown_stop_number', models.IntegerField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('line_id', models.ForeignKey(default=None,
                                              on_delete=django.db.models.deletion.CASCADE, to='main.Line')),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='alert',
            name='user_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='alert_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Alert'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='line_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Line'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='station_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Station'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='alert_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Alert'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='line_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Line'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='station_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Station'),
        ),
    ]
