# Generated by Django 2.2 on 2019-06-16 04:45

from django.db import migrations, models


def seed_lines(apps, schema_editor):
    line_data = [
        {
            'name': '1',
            'group_id': 1,
            'color': '#EE352E',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '2',
            'group_id': 1,
            'color': '#EE352E',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '3',
            'group_id': 1,
            'color': '#EE352E',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '4',
            'group_id': 2,
            'color': '#00933C',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '5',
            'group_id': 2,
            'color': '#00933C',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '6',
            'group_id': 2,
            'color': '#00933C',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '6',
            'group_id': 2,
            'color': '#00933C',
            'text_color': '#FFFFFF',
            'express': True,
        },
        {
            'name': '7',
            'group_id': 3,
            'color': '#B933AD',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': '7',
            'group_id': 3,
            'color': '#B933AD',
            'text_color': '#FFFFFF',
            'express': True,
        },
        {
            'name': 'A',
            'group_id': 4,
            'color': '#0039A6',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'B',
            'group_id': 5,
            'color': '#FF6319',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'C',
            'group_id': 4,
            'color': '#0039A6',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'D',
            'group_id': 5,
            'color': '#FF6319',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'E',
            'group_id': 4,
            'color': '#0039A6',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'F',
            'group_id': 5,
            'color': '#FF6319',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'G',
            'group_id': 6,
            'color': '#6CBE45',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'J',
            'group_id': 7,
            'color': '#996633',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'L',
            'group_id': 8,
            'color': '#A7A9AC',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'M',
            'group_id': 5,
            'color': '#FF6319',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'N',
            'group_id': 9,
            'color': '#FCCC0A',
            'text_color': '#000000',
            'express': False,
        },
        {
            'name': 'Q',
            'group_id': 9,
            'color': '#FCCC0A',
            'text_color': '#000000',
            'express': False,
        },
        {
            'name': 'R',
            'group_id': 9,
            'color': '#FCCC0A',
            'text_color': '#000000',
            'express': False,
        },
        {
            'name': 'S',
            'group_id': 10,
            'color': '#808183',
            'text_color': '#FFFFFF',
            'express': False,
        },
        {
            'name': 'W',
            'group_id': 9,
            'color': '#FCCC0A',
            'text_color': '#000000',
            'express': False,
        },
        {
            'name': 'Z',
            'group_id': 7,
            'color': '#996633',
            'text_color': '#FFFFFF',
            'express': False,
        }
    ]

    Line = apps.get_model('main', 'Line')

    for l in line_data:
        line = Line(
            name=l['name'],
            group_id=l['group_id'],
            color=l['color'],
            text_color=l['text_color'],
            express=l['express']
        )

        line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190615_2330'),
    ]

    operations = [
        migrations.RunPython(seed_lines),
    ]
