# Generated by Django 2.2 on 2019-06-16 05:17

from django.db import migrations, models


def seed_stations(apps, schema_editor):
    station_data = [
        {
            'uid': 'w4',
            'name': 'W 4 St',
            'line_name': 'B',
            'uptown_stop_number': '32',
            'downtown_stop_number': '12'
        },
        {
            'uid': 'w4',
            'name': 'W 4 St',
            'line_name': 'D',
            'uptown_stop_number': '31',
            'downtown_stop_number': '8'
        },
        {
            'uid': 'bwl',
            'name': 'Broadway-Lafayette',
            'line_name': 'D',
            'uptown_stop_number': '30',
            'downtown_stop_number': '9'
        },
    ]

    Line = apps.get_model('main', 'Line')
    Station = apps.get_model('main', 'Station')

    for s in station_data:
        line = Line.objects.filter(name=s['line_name']).first()

        station = Station(
            uid=s['uid'],
            name=s['name'],
            line_id=line,
            uptown_stop_number=s['uptown_stop_number'],
            downtown_stop_number=s['downtown_stop_number'],
        )

        station.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190616_0445'),
    ]

    operations = [
        migrations.RunPython(seed_stations),
    ]
