# Generated by Django 2.2 on 2019-06-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190616_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='line_id',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='alert_id',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='line_id',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='line_id',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='alert_id',
            new_name='alert',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='trip',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
