# Generated by Django 2.2 on 2019-06-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190617_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='uid',
        ),
        migrations.AddField(
            model_name='line',
            name='route',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='mta_downtown_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='mta_uptown_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
