# Generated by Django 2.2 on 2019-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190619_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, max_length=10)),
                ('route', models.CharField(blank=True, max_length=10)),
                ('arrival', models.IntegerField(blank=True)),
            ],
        ),
    ]
