# Generated by Django 2.2 on 2019-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='arrival',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
