# Generated by Django 2.2 on 2019-06-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190626_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='arrival',
            field=models.IntegerField(blank=True),
        ),
    ]
