# Generated by Django 2.2 on 2019-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190626_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='arrivaltime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
